# This is a basic workflow to help you get started with Actions

name: Linters

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: [ fb-pipeline-test ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  front-linter:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '14'
        
      - run: yarn install
        working-directory: './scrutia-frontend'
      - run: yarn run lint --no-fix
        working-directory: './scrutia-frontend'


  run-linters:
    name: api-linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          coverage: none
          tools: composer

      - name: Install PHP dependencies
        run: |
          cd ./scrutia-api
          composer install

      - name: Run linters
        run: |
          cd ./scrutia-api
          ./vendor/bin/phpcs
