# This is a basic workflow to help you get started with Actions

name: main_api_test

# Controls when the workflow will run
on:
  pull_request:
    branches: [ fb-pipeline_test ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  phpunit:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Validate composer.json and composer.lock
      run: |
        cd scrutia-api
        composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        working-directory: 'scrutia-api'
        path: ./scrutia-api/vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: |
        cd scrutia-api
        composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    - name: Run test suite
      run: |
        cd scrutia-api
        ./vendor/bin/sail up -d
        ./vendor/bin/sail php artisan test --testsuite=Unit --coverage --min=50
