# This is a basic workflow to help you get started with Actions

name: main_front_test

# Controls when the workflow will run
on:
  pull_request:
    branches: [ fb-pipeline_test ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  unit-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: setup yarn, with cache for dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'yarn'
          cache-dependency-path: 'scrutia-frontend/yarn.lock'
        
#       - name: move to frontend
#         run: cd scrutia-frontend
        
      - run: yarn install
        working-directory: './scrutia-frontend'
      - run: yarn build
        working-directory: './scrutia-frontend'
      - run: yarn run test:unit
        working-directory: './scrutia-frontend'



        
      
